GastroMan/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.auth import views as auth_views







urlpatterns = [

    #url(r'^api-auth/',include('rest_framework.urls',namespace='rest_framework')),
    url(r'^api_login/',views.UserLoginRESTView.as_view(),name='API_login'),

    url(r'^$',views.IndexView.as_view(),name='home'),
    url(r'^register/$',views.UserFormView.as_view(),name='register'),
    url(r'^login/$', auth_views.login,{'template_name': 'pages-login.html'},name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^change-password/$', views.change_password, name='change-password'),
    url(r'^admin/', admin.site.urls),
    url(r'^stock/', include('stock.urls'),name='stock'),
    #url(r'^avatar/', include('avatar.urls')),
]

stock/urls.py
from django.conf.urls import url, include
from . import views
from rest_framework import routers




router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)


app_name = 'stock'

urlpatterns = [

    #############DATA-URLS#######

    url(r'^api/chart/consum_data_mth$',views.ConsumDataMonths.as_view(),name='consum-data-month'),
    url(r'^api/chart/consum_data_evt/(?P<string>[\w\-]+)$',views.ConsumDataEvents.as_view(),name='consum-data-event'),




    ###########END DATA-URLS#######


    ######## REST_FRAMEWORK #########

    url(r'^api-auth/', include('rest_framework.urls',namespace='rest_framework')),
    url(r'^rest_api/',include(router.urls)),
    url(r'^rest_event_user/(?P<string>[\w\-]+)/',views.EventRESTView.as_view(),name='event_restview'),



    ##### END REST_FRAMEWORK ########





    url(r'^$',views.StocksOverview.as_view(),name='index'),


    url(r'^stockoverview/',views.StocksOverview.as_view(),name='stockoverview'),
    url(r'^stock/add$',views.stock_create,name='stock-create'),
    url(r'^(?P<pk>[0-9]+)/$',views.StockDetailView.as_view(),name='details'),
    url(r'^stock/updt$',views.StockUpdate.as_view(),name='stock-update'),
    url(r'^stock/(?P<pk>[0-9]+)/delete/$',views.StockDelete.as_view(),name='stock-delete'),


    #find stock url by ID



    #Create new Stock/Item

    url(r'^item/add/(?P<pk>[0-9]+)$',views.item_create,name='item-create'),
    url(r'^item/(?P<pk>[0-9]+)$',views.ItemUpdate.as_view(),name='item-update'),
    url(r'^item/(?P<pk>[0-9]+)/delete/$',views.ItemDelete.as_view(),name='item-delete'),




    url(r'^storeoverview/$',views.store_overview,name='storeoverview'),


    #Logistik
    url(r'^storelogistic/fill/(?P<pk>[0-9]+)/(?P<pk2>[0-9]+)$',views.FillItem.as_view(),name='item-fill'),
    url(r'^storelogistic/(?P<pk>[0-9]+)/$',views.StoreLogistic.as_view(),name='store-log'),
    url(r'^storelogistic/(?P<pk>[0-9]+)/(?P<pk2>[0-9]+)/$',views.store_detail_log,name='store-detail-log'),
    url(r'^storelogistic/fill/(?P<pk>[0-9]+)/(?P<pk2>[0-9]+)/(?P<string>[\w\-]+)/$',views.fill_obj_fill,name='fill-obj-fill'),
    url(r'^storelogistic/(?P<pk>[0-9]+)/delete$',views.fill_man_delete,name='fill_man-delete'),


    url(r'^store/(?P<pk>[0-9]+)/delete/$',views.StoreDelete.as_view(),name='store-delete'),
    url(r'^store/create$',views.store_create,name='store-create'),
    url(r'^store/(?P<pk>[0-9]+)$',views.StoreDetail.as_view(),name='store-detail'),
    url(r'^store/reset/(?P<pk>[0-9]+)$',views.store_reset,name='reset-store'),



    url(r'^store/fill/storemanager/(?P<pk>[0-9]+)$',views.add_item_to_store, name='additemtostore'),
    url(r'^store/add/$',views.storeManager_create ,name='storemanager-add'),


    url(r'^menu/$',views.MenuOverview.as_view(),name='menu-overview'),
    url(r'^menu/add/$',views.menu_create,name='menu-create'),
    url(r'^menu/(?P<pk>[0-9]+)/$',views.MenuDetailView.as_view(),name='menu-detail'),
    url(r'^menu/storeitem/add$',views.storeItem_create,name='storeitem-create'),
    url(r'^menu/storeitem/delete/(?P<pk>[0-9]+)/$',views.delete_menu_item,name='delete-menu-item'),

    #Update Stock/Item

    #DeleteView   :TODO:Delete Confirmation

    #Bestellung

    #url(r'^stock/(?P<pk>[0-9]+)$',views.OrderView.as_view(),name='order'),
    #url(r'^ordermanager/add$',views.OrderCreate.as_view(),name='ordermanager'),
    #url(r'^order/(?P<pk>[0-9]+)$',views.passOrderView.as_view(),name='passorder'),


    #Lieferanten
    url(r'^supplier/add$',views.SupplierCreate.as_view(),name='supplier-add'),
    url(r'^supplieroverview/$',views.SupplierOverview.as_view(),name='supplieroverview'),



    #Calender und Events
    url(r'^calendar/$',views.calendar,name='calendar'),
    url(r'^event/add/$',views.event_create,name='event-create'),
    url(r'^event/detail/(?P<pk>[0-9]+)$',views.event_detail,name='event-detail'),
    url(r'^event/begin/(?P<pk>[0-9]+)$',views.event_begin,name='event-begin'),
    url(r'^event/end/(?P<pk>[0-9]+)$',views.event_end,name='event-end'),
    url(r'^event/(?P<pk>[0-9]+)/delete/$',views.event_delete,name='event-delete'),

    #url(r'^role/add/(?P<pk>[0-9]+)/(?P<pk2>[0-9]+)$',views.role_create,name='role-create'),


    url(r'^role/add/(?P<pk>[0-9]+)$',views.role_create,name='role-create'),
    url(r'^role/(?P<pk>[0-9]+)/delete/$',views.role_delete,name='role-delete'),




    #Verzehr(consum)

    url(r'^consum/(?P<pk>[0-9]+)/(?P<string>[\w\-]+)$',views.consum_storeitem_by_type,name='consum-storeitem-by-type'),
    url(r'^consum/store/(?P<pk>[0-9]+)/$',views.consum_thk,name='consum-store'),
    url(r'^consum/(?P<pk>[0-9]+)/$',views.consum_item,name='consum-item'),
    url(r'^add_item_to_consum/$',views.add_item_to_consum,name='add-item-to-consum'),

   ### Lieferung (delivery)
   url(r'^delivery/(?P<pk>[0-9]+)/$',views.delivery_enter,name='delivery-enter'),
   url(r'^delivery/save/(?P<pk>[0-9]+)/$',views.delivery_save,name='delivery-save'),

   ###### Journal ######
   url(r'^journal/$',views.journal_overview,name='journal'),


   ########Export#######

   url(r'^export/(?P<pk>[0-9]+)/$',views.export_to_xls,name='export-to-xls'),




]

stock/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import post_save, post_init
from django.core.validators import RegexValidator
from django.dispatch import receiver
from django.contrib.auth.models import User, Group
from django import forms
from colorful.fields import RGBColorField



from datetime import date
import datetime
import decimal


class UserProfile(models.Model):
    user = models.OneToOneField(User)





class Stock(models.Model):
    name = models.CharField(max_length=250)
    date_of_creation = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name


    def getDateOfCreation(self):
        return self.date_of_creation

    def getName(self):
        return self.name

    def get_absolute_url(self):
        return reverse('stock:details',kwargs={'pk':self.pk})



class Item(models.Model):
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    on_stock = models.IntegerField(null=True,blank=True)

    unit_over=models.DecimalField(max_digits=5,decimal_places=2,default=0.0)
    #on_store = models.IntegerField()
    on_stock_target = models.IntegerField(null=True,blank=True)
    #   on_store_target = models.IntegerField()
    on_stock_min = models.IntegerField(null=True,blank=True)
    to_order=models.IntegerField(default=0)
    filled=models.IntegerField(default=0)
    price=models.DecimalField(max_digits=5,decimal_places=2,default=0.0)


    item_per_st = models.IntegerField(null=True,blank=True)
    #on_store_min = models.IntegerField()
    TYPE =(
        ('WW','Weisswein'),
        ('RW','Rotwein'),
        ('SP','Spirituosen'),
        ('BR','Bier'),
        ('BRF','Bierflasche'),
        ('AFG','Alkoholfrei'),
        ('MIX','Zum mixen'),
    )
    type=models.CharField(max_length=3,choices=TYPE)

    SIZE = (
        ('1','1L'),
        ('33','0,33L'),
        ('4','0,4L'),
        ('5','0,5L'),
        ('75','0,75L'),
        ('25','0,25'),
        ('7','0,7'),
        ('15','1,5'),
        ('375','0,375')

    )

    size=models.CharField(max_length=3,choices=SIZE )
    def __str__(self):
        return self.name+"-->"+self.stock.name

    def get_absolute_url(self):
        return reverse('stock:details', args=(self.stock.pk,))

    def first_letter(self):
        return self.name and self.name[0] or ''


    @property
    def toOrder(self):
        self.to_order=self.on_stock_target-self.on_stock
        self.save()
        return self.to_order


    def substractOnStockChange(self,c_to_substract,u_to_substract):
        if u_to_substract > self.unit_over:
            self.on_stock=self.on_stock-(c_to_substract+1)
            self.unit_over=self.item_per_st-(u_to_substract-self.unit_over)
            self.save()

        else :
            self.unit_over=self.unit_over-u_to_substract
            self.on_stock=self.on_stock-c_to_substract
            self.save()






#<-------Store------>


class StoreManager(models.Model):
    item = models.ForeignKey('Item')
    name = models.CharField(max_length=250)
    store = models.ForeignKey('Store')
    on_store = models.DecimalField(max_digits=5,decimal_places=2,default=0.0)
    on_store_target = models.IntegerField(default=0)
    toFill = models.IntegerField(default=0)
    #filled = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    def get_on_store(self):
        return self.on_store


    def set_on_store(self,onStore):
        self.on_store= onStore


    def to_fill(self):
        self.toFill=self.on_store_target-self.on_store
        return self.toFill

    #def total_filled(self):
        #self.filled

class Store(models.Model):
    name = models.CharField(max_length=250)
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE)
    user = models.ForeignKey(User,null=True,blank=True)
    items = models.ManyToManyField(Item, through=StoreManager)
    color = RGBColorField(default='#FF0000')
    def __str__(self):
        return self.name





    def itemCnt(self):
        cnt=0
        for storeman in self.storemanager_set.all():
            cnt=cnt+storeman.on_store
        return cnt



    def itemOnStoreFilter(self):
        filtered=[]
        for strmn in self.storemanager_set.all():
            if strmn.on_store!=0:
                filtered.append(strmn.item)
        return filtered


        #filtered=[]
        #for item in self.stock.item_set.all():
        #    exist=False
        #    for itemOnStock in self.items.all():
        #        if(item == itemOnStock):
        #            exist=True
        #            continue
        #    if exist==False:
        #        filtered.append(item)
#
#        return filtered


#<----------Fill Object------>

@receiver(post_save, sender=Item, dispatch_uid="create_storemanager")
def update_store(sender,instance,created,**kwargs):
    if created:
        for store in instance.stock.store_set.all():
            storemanager=StoreManager.objects.create(item=instance,name=instance.name+" "+store.name,store=store,on_store=0,on_store_target=0)


class FillObject(models.Model):
    user = models.ForeignKey(User)
    event = models.ForeignKey('Event',on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username+'-->'+self.event.name


class FillManager(models.Model):
    item = models.ForeignKey('Item')
    name = models.CharField(max_length=250)
    store = models.ForeignKey(Store)
    fillobject = models.ForeignKey(FillObject,blank=True,null=True,on_delete=models.CASCADE)

    CONT = (
        (0,'0'),
        (1,'1'),
        (2,'2'),
        (3,'3'),
        (4,'4'),
        (5,'5'),
        (6,'6'),
        (7,'7'),
        (8,'8'),
    )
    container = models.IntegerField(default=0,choices=CONT)
    unit = models.IntegerField(default=0,blank=True,null=True)
    to_fill = models.IntegerField(default=0)

    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse('stock:store-detail-log', args=(self.store.pk,self.fillobject.pk))


class Delivery(models.Model):
    delivery_date=models.DateField(auto_now_add=True)
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE)

    def __str__(self):
        return self.delivery_date.strftime("%Y-%m-%d")+" "+self.stock.name


class DeliveryManager(models.Model):
    delivery=models.ForeignKey(Delivery,on_delete=models.CASCADE)
    item =models.ForeignKey(Item)
    delivered= models.IntegerField()

    def __str__(self):
        return self.item.name+"---> "+str(self.delivery)

    def get_absolute_url(self):
        return reverse('stock:details', args=(self.item.stock.pk,))








class Supplier(models.Model):
    name = models.CharField(max_length=250)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message='Tel. Nummer Format: +99999...',code='invalid_phonenumber')
    phone_number = models.CharField(max_length=15, validators=[phone_regex,]) # validators should be a list
    email = models.EmailField(max_length=250)

    def __str__(self):
        return self.name


class Event(models.Model):
    name = models.CharField(max_length=250)
    date = models.DateField(default=datetime.date.today)
    #date_end = models.DateField(default=datetime.date.today)


    color = RGBColorField(default='#FF0000')

    begin = models.BooleanField(default=False)
    end = models.BooleanField(default=False)
    total_personal_consum = models.DecimalField(max_digits=5,decimal_places=2,default=0.0)

    def __str__(self):
        return self.name



    def get_absolute_url(self):
        return reverse('stock:calender')





    @property
    def event_is_past(self):
        return self.end


    @property
    def event_began(self):
        if self.begin and not self.end:
            return True
        elif self.begin and self.end:
            return False



    @property
    def calc_total_personal_sum(self):
        for consum in self.consum_set.all():
            self.total_personal_consum=self.total_personal_consum+consum.sum
        return self.total_personal_consum



class EventLog(models.Model):
    event=models.ForeignKey(Event,on_delete=models.CASCADE)
    item = models.ForeignKey(Item)
    c_filled = models.IntegerField(null=True,blank=True)
    u_filled = models.IntegerField(null=True,blank=True)
    sales = models.DecimalField(max_digits=11,decimal_places=2,default=0.0)

    def norm_unit_to_container(self):
        div=self.u_filled//self.item.item_per_st
        print(div)
        if div != 0:
            self.c_filled=self.c_filled+div
            self.u_filled=self.u_filled % self.item.item_per_st

    def calc_sales(self):
        self.sales=decimal.Decimal(self.c_filled*self.item.item_per_st)*self.item.price+decimal.Decimal(self.u_filled)*self.item.price

    def __str__(self):
        return self.item.name+'-->'+self.event.name







class RoleManager(models.Model):
    ROLE = (
        ('CVD','CVD'),
        ('CVD_LOG','CVD & Logistik'),

        ('THK','Theke'),
        ('LOG','Logistik'),
        ('GRD','Garderobe'),
        ('CSS','Kasse'),
        ('DJ','dj')
    )
    role=models.CharField(max_length=10,choices=ROLE,blank=True,null=True)
    store = models.ForeignKey(Store,blank=True,null=True)
    user=models.ForeignKey(User,blank=True,null=True)
    event=models.ForeignKey(Event, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username+'-->'+self.event.name

class Consum(models.Model):
    user=models.ForeignKey(User)
    role=models.CharField(max_length=10,null=True,blank=True)
    event=models.ForeignKey(Event,on_delete=models.CASCADE)
    sum=models.DecimalField(max_digits=5,decimal_places=2,default=0.0)

    def __str__(self):
        return self.user.username+'-->'+self.event.name

    def increment_sum(self,incr_price):
        self.sum=self.sum+incr_price

class consumManager(models.Model):

stock/templates/stock/store_templates/consum_item.html
{% extends 'base.html'%}
{% block logo %}
<a href="{% url 'stock:consum-store' consum.event.id %}" class="logo"><span>Blau</span>NC</a>

{% endblock%}
{% block left-side-bar %}




{% block consum_body %}


{% regroup menu.storeitem_set.all|dictsort:"type" by type as item_by_type %}


<br><br>
{% for type in item_by_type%}

  <div class="col-md-4 col-sm-6 col-xs-12">
  <a href="{% url 'stock:consum-storeitem-by-type' consum.id type.grouper  %}">
        <div class="dashboard-tile detail" style="background-color:#1b819d; color:#FFF">
          <div class="content text-center">
            <h1 style="font-size:5vmin">{% if type.grouper == "LD" %}<span> Longdrinks </span>
            {% elif type.grouper == "KRZ" %}<span> Kurzen/Shots </span>
              {% elif type.grouper == "AFGF" %}<span>AFG-Flaschen </span>
                {% elif type.grouper == "BRF" %}<span> Bierflasche</span>
                  {% elif type.grouper == "AFG" %}<span> Alkoholfrei </span>
                    {% elif type.grouper == "FLS" %}<span> Flaschen </span>
                    {% elif type.grouper == "DZ" %}<span> Dosen (Red Bull,...) </span>
                    {% elif type.grouper == "SKT" %}<span> Sekt </span>
                    {% endif %}

          </h1>
            </div>

          </div>
        </div>
  </a>


{% endfor %}




{% endblock %}




{% block consum_verview%}



<div class="jumbotron">




<div class="col-md-12 col-sm-12 col-xs-12" style="margin-top:20px">


<div class="panel panel-primary">
<div class="panel-heading" style="background-color:#1b819d; border-bottom:5px solid #18758f;">

<h3 class="panel-title">
  Verzehr detail: &nbsp;&nbsp; <b>{{consum.user}}</b>

</h3>
<div class="actions pull-right">
  <i class="fa fa-chevron-down"></i>
  <i class="fa fa-times"></i>
</div>

</div>

<div class="panel-body" style="display:none;">


<table class="table table-responsive table-list table-hover">
<thead >
  <tr>
  <th>Getränk</th>
  <th class="text-center">Price</th>
  <th class="text-center">total</th>
  </tr>
</thead>
<tbody>
{% for item in consum.consummanager_set.all %}
<tr>
  <td >
    <span>{{item.storeitem.name}}</span>
  </td>
  <td class="text-center">
    <span>{{item.storeitem.price}}</span>
  </td>
  <td class="text-center">
    <span>{{item.on_consum}}</span>
  </td>
</tr>


{% endfor %}
</tbody>

</table>
</div>
</div>
</div>
</div>
{% endblock %}


{% endblock %}

stock/templates/stock/store_templates/consum_store.html
{% extends 'base.html'%}
{% load auth_extra %}

{% block logo %}
<a href="{% url 'stock:consum-store' event.id %}" class="logo"><span>Blau</span>NC</a>

{% endblock%}



{% block left-side-bar %}





<div class="tab-wrapper tab-primary" style="margin-left:10px; margin-top:10px;">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#Personal" data-toggle="tab">Verzehr</a>
        </li>
        <li><a href="#Ausgaben" data-toggle="tab">Ausgaben</a>
        </li>
    </ul>





<div class="tab-content">
  <div class="tab-pane active" id="Personal">
{% for consum in consum_list %}
{% if consum.user|has_group:"CHEF"%}
<div class="col-md-3 col-sm-3" >
  <a href="{% url 'stock:consum-item' consum.id %}">
  <div class="dashboard-tile detail" style="background-color:#a32e2e; color:#FFF; margin-top:20px">
    <div class="content">
      <h2>{{consum.user.username}}</h2>
      <h3>{{consum.sum}}&nbsp;€ </h3>



    </div>
    <div class="icon">
      <i>{{consum.user.username}}</i>

    </div>

  </div>
  </a>



</div>

{% elif consum.user|has_group:"PRIV"%}
<div class="col-md-3 col-sm-3" >
  <a href="{% url 'stock:consum-item' consum.id %}">
  <div class="dashboard-tile detail" style="background-color:#0a4d85; color:#FFF; margin-top:20px">
    <div class="content">
      <h2>{{consum.user.username}}</h2>
      <h3>{{consum.sum}}&nbsp;€ </h3>



    </div>
    <div class="icon">
      <i>{{consum.user.username}}</i>

    </div>

  </div>
  </a>

</div>

{% elif consum.user|has_group:"SECURITY"%}
<div class="col-md-3 col-sm-3" >
  <a href="{% url 'stock:consum-item' consum.id %}">
  <div class="dashboard-tile detail" style="background-color:#000000; color:#FFF; margin-top:20px">
    <div class="content">
      <h2>{{consum.user.username}}</h2>
      <h3>{{consum.sum}}&nbsp;€ </h3>



    </div>
    <div class="icon">
      <i>{{consum.user.username}}</i>

    </div>

  </div>
  </a>

</div>

{% else %}
{% if consum.role == "DJ" %}
<div class="col-md-3 col-sm-3" >
  <a href="{% url 'stock:consum-item' consum.id %}">
  <div class="dashboard-tile detail" style="background-color:#c8d711; color:#FFF; margin-top:20px">
    <div class="content">
      <h2>{{consum.user.username}}</h2>
      <h3>{{consum.sum}}&nbsp;€ </h3>



    </div>
    <div class="icon">
      <i>{{consum.user.username}}</i>

    </div>

  </div>
  </a>



</div>
{% else %}
<div class="col-md-3 col-sm-3" >
  <a href="{% url 'stock:consum-item' consum.id %}">
  <div class="dashboard-tile detail" style="background-color:#2cbb25; color:#FFF; margin-top:20px">
    <div class="content">
      <h2>{{consum.user.username}}</h2>
      <h3>{{consum.sum}}&nbsp;€ </h3>



    </div>
    <div class="icon">
      <i>{{consum.user.username}}</i>

    </div>

  </div>
  </a>



</div>
{% endif %}
{% endif %}
{% endfor %}
</div>
  <div class="tab-pane active" id="Ausgaben">
  </div>
</div>
</div>

{% endblock %}

stock/templates/stock/store_templates/store_thk.html
{% if event.begin == False and event.end == False %}
<div class="container" style="padding-top:20px;">
<form action="{% url 'stock:event-begin' event.id %}" method="post">
  {% csrf_token %}
  <button type="submit" name="button" class="btn btn-success btn-lg btn-block">Schicht Begin</button>

</form>
</div>


{% elif event.begin == True and event.end == False %}






<div class="col-md-5">
  <a href="#">
  <div class="dashboard-tile detail" style="background-color:#1b819d; color:#FFF; margin-top:20px">
    <div class="content">
      <h1>Kasse</h1>


    </div>
    <div class="icon">
      <i> Kasse</i>

    </div>

  </div>
  </a>



</div>




<div class="col-md-5 col-md-offset-0">
  <a href="{% url 'stock:consum-store' event.id %}">
  <div class="dashboard-tile detail" style="background-color:#1b819d; color:#FFF; margin-top:20px">
    <div class="content">
      <h1>Personal verzehr</h1>


    </div>
    <div class="icon">
      <i>Personal verzehr</i>

    </div>

  </div>
  </a>



</div>






{% endif %}

stock/templates/stock/store_templates/storeitem_by_type.html
{% extends 'stock/store_templates/consum_item.html'%}



<br><br>

{% block consum_body %}

<div class="container">


<div class="row">
{% for item in storeitems %}



<div class="col-md-4 col-sm-4 " style="margin-top:20px">
  <a id="itemBtn" role="button" class="btn btn-primary btn-block btn-3d"
					                     href="#"
							                 onclick="addItem({{ item.id }},{{consum.id}});" onmousedown="redOnMouseDown();">
				                        {{ item.name }}<br>&euro;{{ item.price }}
                            </a>

</div>




{% endfor %}
</div>
</div>

<hr><hr>




<div class="container" style="padding-top:20px">



<a href="{% url 'stock:consum-item' consum.id %}" type="button" class="btn btn-group-justified btn-3d btn-danger"><span class="fa fa-arrow-left"></span></a>

</div>



{% endblock %}